model:
  hidden_channels: 256
  encoder:
    name: cftfm
    hidden_channels: 256
    edge_channels: 64
    key_channels: 128
    num_heads: 4
    num_interactions: 6
    cutoff: 10.0
    knn: 48 # kNN Graph
  field:
    name: classifier
    num_filters: 128
    cutoff: 10.0
    knn: 32 # kNN Graph

train:
  seed: 2021
  batch_size: 4
  num_workers: 4
  max_iters: 2_000_000
  val_freq: 5000
  pos_noise_std: 0.1
  max_grad_norm: .inf
  optimizer:
    type: adam
    lr: 1.e-4
    weight_decay: 0
    beta1: 0.99
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.6
    patience: 10
    min_lr: 1.e-5
  transform:
    mask:
      type: mixed
      min_ratio: 0.0
      max_ratio: 1.2
      min_num_masked: 1
      min_num_unmasked: 0
      p_random: 0.5
      p_bfs: 0.25
      p_invbfs: 0.25
    contrastive:
      num_real: 50
      num_fake: 50
      pos_real_std: 0.05
      pos_fake_std: 2.0

dataset:
  name: pl
  path: ./data/crossdocked_pocket10
  split: ./data/split_by_name.pt
